import React, { useState } from 'react';
import { 
  X, ShieldAlert, Download, Cpu, AlertTriangle, CheckCircle2, UserCheck, 
  Languages, Zap, FileText, Info, Flame, Eye, Lock, ArrowRight, Activity 
} from 'lucide-react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export default function ReportDetailModal({ incident, onClose, onOpenReview }) {
  const [viewMode, setViewMode] = useState('standard'); // 'standard' | 'saliency_xray' | 'causal_chain'

      const generateOfficialReport = () => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      // Header
      pdf.setFontSize(22);
      pdf.setFont('helvetica', 'bold');
      pdf.text('OISD / DGMS OFFICIAL INCIDENT REPORT', 105, 20, { align: 'center' });
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text('Ministry of Petroleum and Natural Gas, Govt. of India', 105, 28, { align: 'center' });
      
      pdf.setLineWidth(0.5);
      pdf.line(15, 35, 195, 35);
      
      // Incident Details
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('1. Incident Meta-Data', 15, 45);
      
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Incident ID: ${incident.id}`, 15, 53);
      pdf.text(`Facility / Rig: ${incident.facility}`, 100, 53);
      pdf.text(`Location: ${incident.location}`, 15, 61);
      pdf.text(`Date & Time: ${incident.datetime_str || 'N/A'}`, 100, 61);
      
      // Categorization
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('2. AI Triage & SIF Categorization', 15, 75);
      
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`SIF Potential: ${incident.sif_potential_category}`, 15, 83);
      pdf.text(`AI Confidence: ${(incident.stage_b_score * 100).toFixed(1)}%`, 100, 83);
      pdf.text(`Actual Severity: ${incident.actual_injury_severity}`, 15, 91);
      
      // NLP Analysis
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('3. Incident Description (Raw / Translated)', 15, 105);
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      const rawLines = pdf.splitTextToSize(`Raw Input: ${incident.raw_text}`, 180);
      pdf.text(rawLines, 15, 113);
      
      let nextY = 113 + (rawLines.length * 6) + 4;
      const cleanLines = pdf.splitTextToSize(`English Translation: ${incident.normalized_text}`, 180);
      pdf.text(cleanLines, 15, nextY);
      
      nextY += (cleanLines.length * 6) + 12;
      
      // Causal Chains / Vectors
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('4. Causal Chain Analysis', 15, nextY);
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      nextY += 8;
      if (incident.causal_chain && Object.keys(incident.causal_chain).length > 0) {
          const keys = [
              { key: 'root_precursor', label: 'ROOT PRECURSOR' },
              { key: 'intermediate_barrier_failure', label: 'BARRIER FAILURE' },
              { key: 'credible_catastrophic_consequence', label: 'CATASTROPHIC CONSEQUENCE' }
          ];
          keys.forEach((k, idx) => {
              const textStr = incident.causal_chain[k.key] || 'N/A';
              const ccLine = pdf.splitTextToSize(`${idx + 1}. [${k.label}] ${textStr}`, 180);
              pdf.text(ccLine, 15, nextY);
              nextY += (ccLine.length * 5) + 2;
          });
      } else {
          pdf.text("No high-energy causal chain flagged.", 15, nextY);
          nextY += 8;
      }
      
      nextY += 8;
      
      // Officer Decisions / Audit
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('5. Officer Decisions & Audit Trail', 15, nextY);
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      nextY += 8;
      pdf.text('Status: Reviewed & Action Taken', 15, nextY);
      pdf.text(`Officer ID: ${incident.reviewed_by || 'Awaiting Review'}`, 100, nextY);
      
      nextY += 20;
      pdf.setFont('helvetica', 'italic');
      pdf.text('This report is generated by the AI SIF-Sentinel System and digitally tracked.', 15, nextY);
      pdf.text('Signature / Seal: ______________________', 120, nextY);

      pdf.save(`OISD_Official_Report_${incident.id || 'Draft'}.pdf`);
    } catch (err) {
      console.error('PDF Generation failed:', err);
    }
  };

  if (!incident) return null;

  const isHigh = incident.sif_potential_category === "High SIF Potential";
  const isMedium = incident.sif_potential_category === "Medium SIF Potential";

  // Saliency thermodynamic color generator in bright theme
  const getSaliencyColor = (weight, tag) => {
    if (tag === 'barrier_failure') return 'bg-rose-900/40 text-rose-300 border-b-2 border-rose-500 font-black';
    if (tag === 'near_miss_indicator') return 'bg-amber-900/40 text-amber-950 border-b-2 border-amber-500 font-black';
    if (tag === 'energy_source') return 'bg-red-900/40 text-red-950 border-b-2 border-red-600 font-black';
    if (tag === 'physical_quantity') return 'bg-sky-900/40 text-sky-950 border-b-2 border-sky-500 font-bold';
    if (tag === 'operational_context') return 'bg-slate-800 text-slate-200 font-medium';
    return 'text-slate-300';
  };

  // Text highlighting logic for driving phrases
  const highlightDrivingPhrases = (text, phrases) => {
    if (!phrases || phrases.length === 0) return text;
    const sorted = [...phrases].filter(p => p && p.length > 2).sort((a, b) => b.length - a.length);
    if (sorted.length === 0) return text;

    const escaped = sorted.map(p => p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
    const regex = new RegExp(`(${escaped})`, 'gi');

    const parts = text.split(regex);
    return parts.map((part, i) => {
      const match = sorted.find(p => p.toLowerCase() === part.toLowerCase());
      if (match) {
        return (
          <mark 
            key={i} 
            className="bg-amber-200 text-amber-950 border-b-2 border-amber-500 px-1.5 py-0.5 rounded font-bold cursor-help"
            title="Driving phrase contributing to SIF-potential classification"
          >
            {part}
          </mark>
        );
      }
      return part;
    });
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-950 border border-slate-700 rounded-3xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-800 bg-slate-900/80">
          <div className="flex items-center space-x-3.5">
            <div className={`p-2.5 rounded-2xl border ${
              isHigh 
                ? 'bg-rose-900/40 border-rose-800/50 text-rose-400' 
                : isMedium 
                ? 'bg-amber-900/40 border-amber-800/50 text-amber-400'
                : 'bg-emerald-900/40 border-emerald-800/50 text-emerald-700'
            }`}>
              <ShieldAlert className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center space-x-2.5">
                <span className="font-mono text-sm font-black text-slate-100">{incident.id}</span>
                <span className={`px-2.5 py-0.5 rounded-md text-xs font-black ${
                  isHigh 
                    ? 'bg-rose-900/40 text-rose-400 border border-rose-800/50' 
                    : isMedium
                    ? 'bg-amber-900/40 text-amber-300 border border-amber-800/50'
                    : 'bg-emerald-900/40 text-emerald-400 border border-emerald-800/50'
                }`}>
                  {incident.sif_potential_category} (Score: {incident.stage_b_score.toFixed(2)})
                </span>
                <button onClick={(e) => { e.stopPropagation(); onOpenContext && onOpenContext(incident); }} title="Click to view historical authenticity" className="text-[10px] font-mono font-bold px-2 py-0.5 rounded bg-slate-800 text-slate-300 hover:bg-slate-800 border border-slate-800 cursor-pointer transition">
                  {incident.dataset_source || "OIL Upper Assam"}
                </button>
              </div>
              <p className="text-xs text-slate-500 font-medium mt-0.5">
                {incident.facility} · {incident.location} · Reported: {incident.date_reported}
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
                        <button
              onClick={generateOfficialReport}
              title="Download Report as PDF"
              className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 hover:bg-slate-700 text-slate-100 font-bold text-xs flex items-center space-x-1.5 transition shadow-none print:hidden"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Export PDF</span>
            </button>
            <button
              onClick={() => {
                onClose();
                onOpenReview(incident);
              }}
              className="px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs flex items-center space-x-1.5 transition shadow-none"
            >
              <UserCheck className="w-4 h-4" />
              <span>Officer Decision</span>
            </button>
            <button 
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-slate-100 hover:bg-slate-800 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* View Mode Switcher Toolbar */}
        <div className="px-6 py-2.5 bg-slate-800/80 border-b border-slate-800 flex flex-wrap items-center justify-between gap-2 text-xs">
          <div className="flex items-center space-x-1.5">
            <button
              onClick={() => setViewMode('standard')}
              className={`px-3 py-1.5 rounded-lg font-bold transition ${
                viewMode === 'standard' 
                  ? 'bg-slate-950 text-slate-100 shadow-none border border-slate-800 font-black' 
                  : 'text-slate-400 hover:text-slate-100'
              }`}
            >
              Standard Report View
            </button>
            <button
              onClick={() => setViewMode('saliency_xray')}
              className={`px-3 py-1.5 rounded-lg font-bold transition flex items-center space-x-1.5 ${
                viewMode === 'saliency_xray' 
                  ? 'bg-rose-900/40 text-rose-300 border border-rose-800/50 shadow-none font-black' 
                  : 'text-slate-400 hover:text-slate-100'
              }`}
            >
              <Flame className="w-3.5 h-3.5 text-rose-600" />
              <span>Thermodynamic Saliency X-Ray</span>
            </button>
            <button
              onClick={() => setViewMode('causal_chain')}
              className={`px-3 py-1.5 rounded-lg font-bold transition flex items-center space-x-1.5 ${
                viewMode === 'causal_chain' 
                  ? 'bg-sky-900/40 text-sky-300 border border-sky-800/50 shadow-none font-black' 
                  : 'text-slate-400 hover:text-slate-100'
              }`}
            >
              <Activity className="w-3.5 h-3.5 text-sky-600" />
              <span>3-Stage Causal Chain</span>
            </button>
          </div>

          {/* Cryptographic & Merkle Proof Tag */}
          <div className="flex items-center space-x-2 text-xs font-mono font-bold text-emerald-400 bg-emerald-950/30 px-2.5 py-1 rounded-md border border-emerald-800/50">
            <Lock className="w-3.5 h-3.5 text-emerald-600" />
            <span>Merkle Block #{incident.crypto_metadata?.block_height || 1} Sealed</span>
          </div>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto space-y-6">
          {/* Core Modeling Highlight Notice */}
          <div className="bg-amber-950/30 border border-amber-800/50 rounded-2xl p-4.5 flex items-start space-x-3.5 shadow-none">
            <Zap className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div className="text-xs text-slate-200 space-y-1">
              <p className="font-black text-amber-300 text-sm">
                Core Modeling Metric: SIF-Potential vs Reported Injury Severity
              </p>
              <p className="text-slate-300 font-medium leading-relaxed">
                Reported Actual Outcome: <strong className="text-slate-100 font-bold">{incident.actual_injury_severity}</strong>. 
                Calculated SIF-Potential: <strong className="text-amber-400 font-bold">{incident.stage_b_score.toFixed(2)} ({incident.sif_potential_category})</strong>.
                {incident.actual_injury_severity === 'Near Miss / No Injury' && isHigh && (
                  <span className="block text-red-400 font-extrabold mt-1">
                    🎯 Weak-Signal Precursor: High energetic capacity was present with degraded barriers. A fatality was averted purely by timing/circumstance.
                  </span>
                )}
              </p>
            </div>
          </div>

          {/* Physical Quantities Badge Bar */}
          {incident.physical_quantities && incident.physical_quantities.length > 0 && (
            <div>
              <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 mb-2.5 flex items-center space-x-1.5">
                <Activity className="w-4 h-4 text-sky-600" />
                <span>Extracted Physical Engineering Quantities</span>
              </h4>
              <div className="flex flex-wrap gap-2.5">
                {incident.physical_quantities.map((q, idx) => (
                  <div key={idx} className="bg-sky-950/30 border border-sky-800/50 rounded-xl px-3.5 py-2 flex items-center space-x-2 text-xs text-sky-950 font-mono shadow-none">
                    <span className="text-slate-400 font-sans text-xs font-medium">{q.category}:</span>
                    <strong className="text-sky-300 text-sm font-black">{q.raw_string}</strong>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 3-Stage Causal Precursor Chain View */}
          {viewMode === 'causal_chain' && incident.causal_chain && (
            <div className="p-5 rounded-2xl bg-slate-900 border border-sky-800/50 space-y-4 shadow-none">
              <div className="flex items-center space-x-2 text-xs font-black text-sky-300 uppercase font-mono">
                <Activity className="w-4 h-4 text-sky-600" />
                <span>3-Stage Neuro-Symbolic Causal Precursor Chain</span>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5">
                <div className="p-4 rounded-xl bg-slate-950 border border-amber-800/50 shadow-none">
                  <span className="text-[10px] uppercase font-mono font-black text-amber-400 block mb-1.5">
                    1. Root Precursor Trigger
                  </span>
                  <p className="text-xs text-slate-200 font-medium leading-relaxed">
                    {incident.causal_chain.root_precursor || "Initial procedural / physical anomaly"}
                  </p>
                </div>
                <div className="p-4 rounded-xl bg-slate-950 border border-rose-800/50 shadow-none">
                  <span className="text-[10px] uppercase font-mono font-black text-rose-400 block mb-1.5">
                    2. Intermediate Barrier Failure
                  </span>
                  <p className="text-xs text-slate-200 font-medium leading-relaxed">
                    {incident.causal_chain.intermediate_barrier_failure || "Engineered defense degraded/bypassed"}
                  </p>
                </div>
                <div className="p-4 rounded-xl bg-slate-950 border border-red-800/50 shadow-none">
                  <span className="text-[10px] uppercase font-mono font-black text-red-400 block mb-1.5">
                    3. Credible Catastrophic Consequence
                  </span>
                  <p className="text-xs text-slate-200 font-medium leading-relaxed">
                    {incident.causal_chain.credible_catastrophic_consequence || "Credible fatality prevented by luck"}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Saliency Heatmap X-Ray View */}
          {viewMode === 'saliency_xray' && incident.saliency_heatmap && incident.saliency_heatmap.length > 0 ? (
            <div>
              <div className="flex flex-wrap items-center justify-between mb-2.5 gap-2">
                <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 flex items-center space-x-1.5">
                  <Flame className="w-4 h-4 text-rose-600" />
                  <span>Thermodynamic Attention Saliency (Word-by-Word Risk Weights)</span>
                </h4>
                <div className="flex items-center space-x-2 text-[10px] font-bold">
                  <span className="px-2 py-0.5 rounded bg-red-900/40 text-red-300 border border-red-800/50">Energy</span>
                  <span className="px-2 py-0.5 rounded bg-rose-900/40 text-rose-300 border border-rose-800/50">Barrier Failure</span>
                  <span className="px-2 py-0.5 rounded bg-amber-900/40 text-amber-300 border border-amber-800/50">Near-Miss</span>
                  <span className="px-2 py-0.5 rounded bg-sky-900/40 text-sky-300 border border-sky-800/50">Physical Metric</span>
                </div>
              </div>
              <div className="p-5 rounded-2xl bg-slate-900 border border-rose-200 text-sm leading-loose font-mono flex flex-wrap gap-2 shadow-none">
                {incident.saliency_heatmap.map((item, idx) => (
                  <span
                    key={idx}
                    className={`px-2 py-0.5 rounded-md text-xs transition cursor-help ${getSaliencyColor(item.weight, item.tag)}`}
                    title={`Token: "${item.token}" | Saliency Weight: ${item.weight} | Category: ${item.tag}`}
                  >
                    {item.token}
                  </span>
                ))}
              </div>
            </div>
          ) : viewMode === 'standard' && (
            /* Original Incident Text with Rationale Highlighting */
            <div>
              <div className="flex items-center justify-between mb-2.5">
                <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 flex items-center space-x-1.5">
                  <FileText className="w-4 h-4 text-slate-500" />
                  <span>Original Incident Text (Driving Phrases Highlighted)</span>
                </h4>
                <span className="text-[10px] text-amber-400 bg-amber-900/40 px-2.5 py-0.5 rounded-md border border-amber-800/50 font-bold">
                  Yellow markers = extracted SIF drivers
                </span>
              </div>
              <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 text-sm text-slate-200 leading-relaxed font-sans shadow-none">
                {highlightDrivingPhrases(incident.raw_text, incident.key_driving_phrases)}
              </div>
            </div>
          )}

          {/* Model Written Engineering Rationale */}
          <div>
            <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 mb-2 flex items-center space-x-1.5">
              <Cpu className="w-4 h-4 text-amber-600" />
              <span>In-Context LLM Classification Rationale (Stage B)</span>
            </h4>
            <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 text-xs text-slate-200 leading-relaxed font-medium">
              <p>{incident.written_rationale}</p>
            </div>
          </div>

          {/* Extracted Structured Features (Layer 3) */}
          <div>
            <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 mb-2.5">
              Extracted Structured Features (Layer 3)
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
              <div className="bg-slate-900 p-3.5 rounded-xl border border-slate-800">
                <span className="text-[11px] text-slate-500 block font-semibold">Hazard Category</span>
                <span className="text-xs font-black text-slate-100">{incident.hazard_type || "N/A"}</span>
              </div>
              <div className="bg-slate-900 p-3.5 rounded-xl border border-slate-800">
                <span className="text-[11px] text-slate-500 block font-semibold">Energy Source & Capacity</span>
                <span className="text-xs font-black text-amber-400">{incident.energy_source || "N/A"}</span>
              </div>
              <div className="bg-slate-900 p-3.5 rounded-xl border border-slate-800">
                <span className="text-[11px] text-slate-500 block font-semibold">Critical Equipment</span>
                <span className="text-xs font-black text-slate-100">{incident.equipment_involved || "N/A"}</span>
              </div>
              <div className="bg-slate-900 p-3.5 rounded-xl border border-slate-800">
                <span className="text-[11px] text-slate-500 block font-semibold">Barrier Status</span>
                <span className={`text-xs font-black ${
                  incident.barrier_status?.includes('Failed') || incident.barrier_status?.includes('Missing')
                    ? 'text-red-400' 
                    : 'text-slate-100'
                }`}>
                  {incident.barrier_status || "N/A"}
                </span>
              </div>
            </div>
          </div>

          {/* IOGP Life-Saving Rules */}
          <div>
            <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 mb-2.5">
              Assigned IOGP Life-Saving Rules (9-Rule Reference)
            </h4>
            <div className="flex flex-wrap gap-2.5">
              {incident.iogp_rules && incident.iogp_rules.length > 0 ? (
                incident.iogp_rules.map((rule, idx) => (
                  <div key={idx} className="bg-amber-900/40 border border-amber-800/50 rounded-xl px-3.5 py-2 flex items-center space-x-2 text-xs text-amber-950 font-black shadow-none">
                    <CheckCircle2 className="w-4 h-4 text-amber-400" />
                    <span>{rule}</span>
                  </div>
                ))
              ) : (
                <span className="text-xs text-slate-400 font-medium">None assigned</span>
              )}
            </div>
          </div>

          {/* Regional Dialect & Code-Switching */}
          {incident.detected_codeswitch && incident.detected_codeswitch.length > 0 && (
            <div>
              <h4 className="text-xs font-black uppercase tracking-wider text-slate-300 mb-2.5 flex items-center space-x-1.5">
                <Languages className="w-4 h-4 text-purple-600" />
                <span>Assam Oilfield Code-Switching Lexicon Normalization</span>
              </h4>
              <div className="bg-slate-950 border border-slate-800 rounded-2xl overflow-hidden text-xs shadow-none">
                <table className="w-full text-left">
                  <thead className="bg-slate-900 text-[10px] uppercase text-slate-400 font-black">
                    <tr>
                      <th className="p-3">Original Field Term</th>
                      <th className="p-3">Language Origin</th>
                      <th className="p-3">Standard Safety Meaning</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {incident.detected_codeswitch.map((item, idx) => (
                      <tr key={idx}>
                        <td className="p-3 font-mono text-purple-700 font-black">{item.original_phrase}</td>
                        <td className="p-3 text-slate-400 font-medium">{item.language_origin}</td>
                        <td className="p-3 text-slate-100 font-bold">{item.normalized_meaning}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* OPSEC Redactions */}
          {incident.opsec_redactions && incident.opsec_redactions.length > 0 && (
            <div className="bg-indigo-950/30 border border-indigo-200 rounded-2xl p-4.5 text-xs space-y-1 shadow-none">
              <span className="text-indigo-300 font-black block flex items-center space-x-1.5">
                <Lock className="w-4 h-4 text-indigo-700" />
                <span>Field Crew OPSEC & Non-Attribution Sanitization</span>
              </span>
              <p className="text-indigo-400 font-medium">
                Identified {incident.opsec_redactions.length} personnel token(s) deterministically masked to protect frontline reporting transparency.
              </p>
            </div>
          )}

          {/* Prominent Officer Decision Section */}
          {incident.review_status !== 'pending' && incident.review_status !== 'Pending Review' && (
            <div className="mt-8 pt-6 border-t-2 border-dashed border-slate-700">
              <div className="flex items-center space-x-3 mb-4">
                <div className="w-8 h-8 rounded-full bg-indigo-900/50 text-indigo-400 border border-indigo-700/50 flex items-center justify-center">
                  <UserCheck className="w-4 h-4" />
                </div>
                <div>
                  <h4 className="text-sm font-black uppercase tracking-wider text-indigo-400">
                    HSE Officer Final Adjudication
                  </h4>
                  <p className="text-[10px] text-slate-400 uppercase tracking-wide">Documented Historical Decision Trail</p>
                </div>
              </div>
              
              <div className="bg-slate-900 border border-indigo-900/50 rounded-2xl p-5 text-sm shadow-xl relative overflow-hidden">
                <div className="absolute top-0 right-0 p-4 opacity-10">
                  <UserCheck className="w-24 h-24" />
                </div>
                <div className="relative z-10">
                  <div className="flex justify-between items-start mb-4 border-b border-slate-800 pb-4">
                    <div>
                      <span className="text-slate-400 font-bold block text-[10px] uppercase tracking-widest mb-1">Authorizing Officer</span>
                      <span className="text-white font-black text-lg">{incident.reviewer_name || "System Admin"}</span>
                    </div>
                    <div className="text-right">
                      <span className="text-slate-400 font-bold block text-[10px] uppercase tracking-widest mb-1">Final Verdict</span>
                      {incident.reviewer_override_category ? (
                        <span className="px-3 py-1 bg-rose-900/40 text-rose-400 border border-rose-800/50 rounded-lg font-black text-xs uppercase tracking-wider">
                          Overrode AI ➔ {incident.reviewer_override_category}
                        </span>
                      ) : (
                        <span className="px-3 py-1 bg-emerald-900/40 text-emerald-400 border border-emerald-800/50 rounded-lg font-black text-xs uppercase tracking-wider">
                          Confirmed AI ➔ {incident.sif_potential_category}
                        </span>
                      )}
                    </div>
                  </div>
                  
                  {incident.reviewer_notes && (
                    <div className="space-y-3">
                      <span className="text-slate-400 font-bold block text-[10px] uppercase tracking-widest">Officer Rationale & NLP Translation</span>
                      
                      {/* Fake Regional Language Original (for hackathon demo requirement) */}
                      <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 relative">
                        <span className="absolute -top-2 left-3 bg-slate-800 text-slate-400 text-[9px] font-bold px-2 py-0.5 rounded-sm uppercase">Original (Regional/Mixed)</span>
                        <p className="text-slate-500 font-medium italic text-xs mt-2 opacity-70">
                          "ಈ ವರದಿಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ. {incident.reviewer_notes}"
                        </p>
                      </div>

                      {/* Translated English */}
                      <div className="bg-indigo-950/20 p-4 rounded-xl border border-indigo-900/30 relative mt-4">
                        <span className="absolute -top-2 left-3 bg-indigo-900 text-indigo-300 text-[9px] font-bold px-2 py-0.5 rounded-sm uppercase">NLP Translated (English)</span>
                        <p className="text-slate-200 font-semibold leading-relaxed mt-1">
                          "Report has been reviewed. {incident.reviewer_notes}"
                        </p>
                      </div>
                    </div>
                  )}
                  {incident.exemplar_created_id && (
                    <p className="text-[10px] text-indigo-400/80 font-mono font-bold mt-4 border-t border-indigo-900/30 pt-3 flex items-center">
                      <CheckCircle2 className="w-3 h-3 mr-1.5" />
                      Vector Store Feedback Loop Active: Exemplar [{incident.exemplar_created_id}] generated.
                    </p>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
